name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: PHP CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2, phpunit
          coverage: xdebug

      - name: Validate composer.json And composer.lock
        run: composer validate

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Unit Tests With PHPUnit
        run: ./vendor/bin/phpunit --coverage-clover clover.xml

      - name: Check Code Style With PHP_CodeSniffer
        run: ./vendor/bin/phpcs --standard=./phpcs.xml

      - name: Static Analysis with PHPStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon

      - name: Mutation Testing with Infection
        run: ./vendor/bin/infection --configuration=infection.json --min-msi=70 --min-covered-msi=70
