name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: PHP CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.0' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2, phpunit
          extensions: mbstring
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run Unit Tests with PHPUnit
        run: ./vendor/bin/phpunit --coverage-clover ./coverage.xml

      - name: Mutation Testing with Infection
        run: ./vendor/bin/infection --configuration=infection.json --min-msi=100 --min-covered-msi=100

      - name: Check Code Style with PHP_CodeSniffer
        run: ./vendor/bin/phpcs --standard=./phpcs.xml

      - name: Static Analysis with PHPStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
